"""
FeedbackReport — qualitative AI feedback for a completed attempt.

One row per attempt. Stores strengths, weaknesses, improvement tips, and
a sample high-band response — all generated by the LLM scorer.

Column design:
- strengths / weaknesses / improvement_tips: PostgreSQL JSON columns.
  Each element is a dict { label, observation, quote, fix? } for the new
  rich format, or a plain string for legacy rows.  Both shapes are handled
  gracefully in report_service.py.
- next_milestone / dimension_commentary: new nullable columns added in
  migration 0014.  NULL for all pre-upgrade reports.
"""
from __future__ import annotations

import uuid

from sqlalchemy import Text, ForeignKey, Index
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin


class FeedbackReport(Base, TimestampMixin):
    """Qualitative AI feedback for a scored attempt."""

    __tablename__ = "feedback_reports"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    attempt_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("attempts.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,  # one report per attempt
        index=True,
    )

    # LLM-generated feedback — stored as JSONB arrays of objects (or legacy strings)
    strengths: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    weaknesses: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    improvement_tips: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    sample_response: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Rich coaching fields added in migration 0014 — nullable for pre-upgrade rows
    next_milestone: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)
    dimension_commentary: Mapped[dict | None] = mapped_column(JSONB, nullable=True, default=None)

    __table_args__ = (
        Index("idx_feedback_reports_attempt", "attempt_id"),
    )
