"""
FeedbackReport — qualitative AI feedback for a completed attempt.

One row per attempt. Stores strengths, weaknesses, improvement tips, and
a sample high-band response — all generated by the LLM scorer.

PostgreSQL ARRAY columns are used for list fields (simpler than JSON for
this use case; frontend reads them as plain arrays).
"""
from __future__ import annotations

import uuid

from sqlalchemy import Text, ForeignKey, Index
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin


class FeedbackReport(Base, TimestampMixin):
    """Qualitative AI feedback for a scored attempt."""

    __tablename__ = "feedback_reports"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    attempt_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("attempts.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,  # one report per attempt
        index=True,
    )

    # LLM-generated feedback — stored as Postgres text arrays
    strengths: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, default=list
    )
    weaknesses: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, default=list
    )
    improvement_tips: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, default=list
    )
    sample_response: Mapped[str] = mapped_column(Text, nullable=False, default="")

    __table_args__ = (
        Index("idx_feedback_reports_attempt", "attempt_id"),
    )
