"use client";

// ─────────────────────────────────────────────────────────────────────────────
// TranscriptCard.tsx — Whisper STT transcript (speaking only, collapsible)
// ─────────────────────────────────────────────────────────────────────────────

import { useState } from "react";
import { ChevronDown } from "lucide-react";

interface Props {
  transcript: string;
}

export function TranscriptCard({ transcript }: Props) {
  const [open, setOpen] = useState(false);

  if (!transcript) return null;

  const wordCount = transcript.trim().split(/\s+/).length;

  return (
    <div className="rounded-2xl border border-border bg-surface shadow-card overflow-hidden">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center justify-between px-5 py-4 text-left hover:bg-white/[0.02] transition-colors"
        aria-expanded={open}
      >
        <div className="flex items-center gap-2">
          <span className="text-lg">📝</span>
          <span className="text-sm font-semibold uppercase tracking-wider text-subtle">
            Your Transcript
          </span>
          <span className="rounded-full bg-surface border border-border px-2 py-0.5 text-xs text-subtle">
            ~{wordCount} words
          </span>
        </div>
        <ChevronDown
          className={`h-4 w-4 text-subtle transition-transform duration-200 ${open ? "rotate-180" : ""}`}
        />
      </button>

      <div
        className="overflow-hidden transition-all duration-300 ease-in-out"
        style={{ maxHeight: open ? "600px" : "0px" }}
      >
        <div className="border-t border-border px-5 py-4">
          <p className="text-sm leading-relaxed text-white/70 font-mono whitespace-pre-wrap">
            {transcript}
          </p>
          <p className="mt-3 text-xs text-subtle">
            Auto-generated by Whisper STT — minor transcription errors may occur.
          </p>
        </div>
      </div>
    </div>
  );
}
