"""Slug helpers — used by the bulk prompt importer to derive and de-duplicate slugs.

Prompt slugs are UNIQUE in the DB but are NOT auto-generated by the single-create
endpoints (they pass the field through verbatim). The bulk importer needs to (a)
derive a slug from a title when none is supplied, and (b) guarantee that derived
slug is unique against both the DB and the rest of the same import batch.
"""
import re

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(text: str | None) -> str:
    """Turn arbitrary text into a URL-safe slug. Returns "" for empty input."""
    if not text:
        return ""
    lowered = text.strip().lower()
    collapsed = _SLUG_RE.sub("-", lowered)
    return collapsed.strip("-")


def unique_slug(base: str, taken: set[str]) -> str:
    """Return `base`, or `base-2`, `base-3`, … — the first value not in `taken`.

    Does NOT mutate `taken`; the caller is responsible for adding the returned
    value so later rows in the same batch see it.
    """
    candidate = base or "prompt"
    if candidate not in taken:
        return candidate
    n = 2
    while f"{candidate}-{n}" in taken:
        n += 1
    return f"{candidate}-{n}"
